# This file goes in: dean0x/homebrew-tap/.github/workflows/update-formula.yml
name: Update Mars Formula

on:
  repository_dispatch:
    types: [mars-release]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get release info
        id: release
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Updating formula to version: $VERSION"

      - name: Download and calculate SHA256
        id: sha
        run: |
          VERSION="${{ steps.release.outputs.version }}"
          TARBALL_URL="https://github.com/dean0x/mars/archive/refs/tags/v${VERSION}.tar.gz"

          curl -sL "$TARBALL_URL" -o mars.tar.gz
          SHA256=$(sha256sum mars.tar.gz | cut -d' ' -f1)

          echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"
          echo "SHA256: $SHA256"

      - name: Update Formula
        run: |
          VERSION="${{ steps.release.outputs.version }}"
          SHA256="${{ steps.sha.outputs.sha256 }}"

          cat > Formula/mars.rb << EOF
          class Mars < Formula
            desc "Multi Agentic Repo workspace manager for Git repositories"
            homepage "https://github.com/dean0x/mars"
            url "https://github.com/dean0x/mars/archive/refs/tags/v${VERSION}.tar.gz"
            sha256 "${SHA256}"
            license "MIT"

            def install
              bin.install "dist/mars"
            end

            test do
              system "#{bin}/mars", "--version"
            end
          end
          EOF

      - name: Commit and push
        run: |
          VERSION="${{ steps.release.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/mars.rb
          git commit -m "Update mars to v${VERSION}"
          git push
